int eno;
string ename;
float esal;
double epf;
string egrade;
bool ews;
Console.WriteLine("Enter Employee Number");
eno = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Enter Employee Name");
ename = Console.ReadLine();
Console.WriteLine("Enter Employee Salary");
esal = (float)Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Enter Employee PF");
epf = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Enter Employee Grade");
egrade = Console.ReadLine();
Console.WriteLine("Enter Employee Working Status(true/false):");
ews = Convert.ToBoolean(Console.ReadLine());
Console.Clear();
Console.WriteLine("------------------------------");
Console.WriteLine("Employee Details");
Console.WriteLine("------------------------------");
Console.WriteLine("Employee Number : " + eno);
Console.WriteLine("Employee Name : " + ename);
Console.WriteLine("Employee Salary : " + esal);
Console.WriteLine("Employee PF : " + epf);
Console.WriteLine("Employee Grade : " + egrade);
Console.WriteLine("Employee Working Status : " + ews);
Console.WriteLine("------------------------------");