using System;
int sno;
string name;
int sclass;
string ssec;
int m1, m2, m3, m4, m5, m6, tot;
float avg;
Console.WriteLine("Enter the student number");
sno = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Enter the student name");
name = Console.ReadLine();
Console.WriteLine("Enter the student class");
sclass = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Enter the student section");
ssec = Console.ReadLine();
Console.WriteLine("Enter the marks of m1");
m1 = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Enter the marks of m2");
m2 = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Enter the marks of m3");
m3 = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Enter the marks of m4");
m4 = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Enter the marks of m5");
m5 = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Enter the marks of m6");
m6 = Convert.ToInt32(Console.ReadLine());
tot = m1 + m2 + m3 + m4 + m5 + m6;
avg = tot / 6;
System.Console.Clear();
System.Console.WriteLine("======================================");
System.Console.WriteLine("Student Details");
System.Console.WriteLine("======================================");
System.Console.WriteLine("Student Number: " + sno);
System.Console.WriteLine("Student Name: " + name);
System.Console.WriteLine("Student Class: " + sclass);
System.Console.WriteLine("Student Section: " + ssec);
System.Console.WriteLine("****************************************");
System.Console.WriteLine("Marks of m1: " + m1+"\t"+"m2="+m2+"\t"+"m3"+m3);
System.Console.WriteLine("Marks of m4: " + m4 + "\t" + "m5=" + m5 + "\t" + "m6" + m6);
System.Console.WriteLine("****************************************");
System.Console.WriteLine("Total Marks: " + tot);
System.Console.WriteLine("Average Marks: " + avg);
System.Console.WriteLine("======================================");